### Listar Usuários
GET http://localhost:3000/usuarios

### Listar TODOS os chamados (padrão: 10 itens da página 1)
GET http://localhost:3000/chamados
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3ODY4MzkwMjQsImV4cCI6MTc4Njg2NzgyNH0.VH57Dd6UosNW4t-E1kh2hp0lLaLn_RaCvmevTTxezGM

### Listar apenas chamados Abertos (Filtro simples)
GET http://localhost:3000/chamados?status=Aberto
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3ODY4MzQyODYsImV4cCI6MTc4Njg2MzA4Nn0.ON2sXKVnMOQXQp_vUqaL1Lkv6w0Y4k15-FSA4GR2NrE

### Listar com múltiplos filtros e paginação (Página 2, limite de 5 por página)
GET http://localhost:3000/chamados?status=Aberto&priority=Alta&page=2&limit=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3ODY4MzQyODYsImV4cCI6MTc4Njg2MzA4Nn0.ON2sXKVnMOQXQp_vUqaL1Lkv6w0Y4k15-FSA4GR2NrE

### Criar Usuário
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "username": "william_user",
  "role": "usuario",
  "email": "william_user@teste.com",
  "password_hash": "senha123"
}

### Criar Usuário errado
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "username": "william_error",
  "role": "usuario",
  "email": "william_error-teste.com",
  "password_hash": "senha123"
}

### Criar Usuário Admin
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "username": "william_admin",
  "role": "admin",
  "email": "william_admin@teste.com",
  "password_hash": "senha1234"
}

### Criar Chamado
POST http://localhost:3000/chamados
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3ODY4MzQ0MTgsImV4cCI6MTc4Njg2MzIxOH0.wxc81a3uS-bNRh8ZfSC_wvHKJvE55J6ZSZLgowO8t-c

{
  "title": "huehuebrbr",
  "status": "Em andamento",
  "priority": "Baixa",
  "category": "Outros",
  "description": "if you really wanna know what they doing in tokyo"
}

### Fazer Login Admin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "william_admin@teste.com",
  "password": "senha1234"
}

### Fazer Login Usuário
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "william_user@teste.com",
  "password": "senha123"
}

### Atualizar Chamado
PATCH http://localhost:3000/chamados/6
Content-Type: application/json

{
  "status": "Em andamento"
}

### Excluir Chamado
DELETE http://localhost:3000/chamados/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzg2NTUzOTA2LCJleHAiOjE3ODY1ODI3MDZ9.a9oz8ylLdsGc_SXSQZcaQ3-1IML1afnVx9VSHfVXFls

### Adicionar Comentário no Chamado
POST http://localhost:3000/chamados/5/comentarios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3ODY4MzkwMjQsImV4cCI6MTc4Njg2NzgyNH0.VH57Dd6UosNW4t-E1kh2hp0lLaLn_RaCvmevTTxezGM

{
  "message": "Olá, já reiniciei o computador e o problema persiste. Podem me ajudar?"
}

### Listar Comentários de um Chamado
GET http://localhost:3000/chamados/5/comentarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3ODY4NDQwMTQsImV4cCI6MTc4Njg3MjgxNH0.Q8VHeM9imFsrIPR6h_zahH24_asgHas8WF7aYUt6ep8

### Buscar Chamado Específico por ID
GET http://localhost:3000/chamados/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3ODY4NDQwMTQsImV4cCI6MTc4Njg3MjgxNH0.Q8VHeM9imFsrIPR6h_zahH24_asgHas8WF7aYUt6ep8

### Atualizar Perfil de Usuário
PUT http://localhost:3000/usuarios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3ODY4NDQwMTQsImV4cCI6MTc4Njg3MjgxNH0.Q8VHeM9imFsrIPR6h_zahH24_asgHas8WF7aYUt6ep8

{
  "username": "novo_username",
  "email": "novo_email@teste.com"
}

### Atualizar apenas senha do usuário
PUT http://localhost:3000/usuarios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3ODY4NDQwMTQsImV4cCI6MTc4Njg3MjgxNH0.Q8VHeM9imFsrIPR6h_zahH24_asgHas8WF7aYUt6ep8

{
  "password_hash": "nova_senha_super_segura"
}

### Fazer Logout
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3ODY4NDQwMTQsImV4cCI6MTc4Njg3MjgxNH0.Q8VHeM9imFsrIPR6h_zahH24_asgHas8WF7aYUt6ep8